version: 1

sources:
  - name: enpal
    database: postgres
    schema: public
    tables:
      - name: activity
      - name: activity_types
      - name: deal_changes
      - name: fields
      - name: stages
      - name: users
